config/routes.rb
Rails.application.routes.draw do
  resources :slots
  root to: "demo#index"
  devise_for :users

  resources :nannies do
    member do
      patch :reserve
      delete :cancel
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :user
  has_many :slots

  def name
    user.name
  end
end

app/models/nanny.rb
class Nanny < ApplicationRecord
  belongs_to :user
  has_many :slots, dependent: :destroy

  validates :user_id, presence: true

  def name
    user.name
  end
end

app/models/slot.rb
class Slot < ApplicationRecord

  belongs_to :family, optional: true
  belongs_to :nanny

  START_BUFFER = 15.minutes
  MINIMUM_DURATION = 30.minutes

  validates :start_time, presence: true
  validates :end_time, presence: true

  # The ordering of these validations is important
  validate :cannot_be_in_past, on: :create
  validate :end_must_greater_than_start
  validate :no_overlaps

   scope :reserveable, -> { where(family_id: nil) }

  def can_reserve?
    family_id.nil?
  end

  def reserve_for(family)
    if can_reserve?
      self.family = family
      self.save!
    else
      raise "slot is already reserved"
    end
  end

  def can_cancel?(resource)
    case resource
    when Family then family.id == resource.id
    when Nanny then resource.id == nanny_id && family_id.nil?
    else
      false
    end
  end

  def can_edit?(resource)
    can_cancel?(resource)
  end

  def cannot_be_in_past
    return unless start_time
    if start_time < Time.now
      errors.add(:start_time, "cannot be in the past")
    end

    if start_time > Time.now && start_time < Time.now + START_BUFFER
      errors.add(:start_time, "slot must start atleast #{START_BUFFER.to_i/60} minutes from now")
    end
  end

  def end_must_greater_than_start
    return unless start_time && end_time
    if end_time < (start_time + MINIMUM_DURATION)
      errors.add(:end_time, "must be a minimum of 30 minutes more than start time")
    end
  end

  def no_overlaps
    return unless self.nanny
    found_overlaps = self.nanny.slots.where("start_time < ? AND ? < end_time", self.end_time, self.start_time)

    # This is needed to prevent a race condition where it finds itself on subsequent saves.
    found_overlaps = found_overlaps.where("slots.id != ?", self.id) if self.persisted?

    if found_overlaps.any?
      errors.add(:start_time, "you already have a slot booked in this time period")
    end
  end

  def can_change_start_time?
    !family_id.present?
  end


end

app/models/user.rb
class User < ApplicationRecord

  has_one :nanny, dependent: :destroy
  has_one :family, dependent: :destroy

  validates :name, presence:true
  validates :default_type, presence:true, inclusion: { in: %w(nanny family) }

  after_commit :create_nanny_or_family, on: [:create]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # removed :recoverable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable


  def is_nanny?
    "nanny" == default_type
  end

  def is_family?
    "family" == default_type
  end

  private
  def create_nanny_or_family
    case default_type
    when "nanny"
      self.create_nanny!
    when "family"
      self.create_family!
    else
      raise StandardError.new("Attribute default type is not set or invalid")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :default_type])
    end

    def after_sign_in_path_for(resource)
      case resource.default_type
      when "nanny"
        slots_path
      when "family"
        nannies_path
      end
    end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  def index
    redirect_to after_sign_in_path_for(current_user)
  end
end

app/controllers/nannies_controller.rb
class NanniesController < ApplicationController
  def index
    @start_time = params[:start_time].present? ? parse_datetime(params[:start_time]) : Time.now + 1.days
    @end_time = params[:end_time].present? ? parse_datetime(params[:end_time]) : @start_time + 10.days

    @nannies = Nanny.joins(:slots).
                    where("slots.start_time >= ? && slots.end_time <= ?", @start_time, @end_time).
                    includes(:slots).
                    order("slots.start_time ASC").
                    merge(Slot.reserveable)
  end

  def show
    @nanny = Nanny.find(params[:id])
  end

  def reserve
    @slot = Slot.includes(:nanny).find(params[:id])
    family = current_user.family
    nanny = @slot.nanny

    if @slot.can_reserve? && @slot.reserve_for(family)
      redirect_to nannies_path, notice: "successfully reserved #{nanny.name} from #{helpers.format_time(@slot.start_time)} to #{helpers.format_time(@slot.end_time)}"
    else
      redirect_to nannies_path(nanny), alert: "slot cannot be reserved"
    end
  end

  def cancel
  end

  def parse_datetime(hash)
    datetime = []
    datetime << hash[:year]
    datetime << hash[:month]
    datetime << hash[:day]
    datetime << hash[:hour]
    datetime << hash[:minute]
    DateTime.strptime(datetime.join("-"), "%Y-%m-%d-%H-%M")
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :set_slot, only: [:show, :edit, :update, :destroy]

  def index
    @slots = current_user.nanny.slots
  end

  def show
  end

  def new
    @slot = Slot.new
    @slot.start_time = Time.now + Slot::START_BUFFER + 5.minutes
    @slot.end_time = @slot.start_time + Slot::MINIMUM_DURATION
  end

  def edit
    return slots_path, notice: "This slot has been reserved and cannot be changed" unless @slot.can_edit?(current_user.nanny)
  end

  def create
    @slot = Slot.new(slot_params)
    @slot.nanny = current_user.nanny

    respond_to do |format|
      if @slot.save
        format.html { redirect_to slots_path, notice: 'Slot was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    if @slot.can_edit?(current_user.nanny)
      if @slot.update(slot_params)
        return redirect_to @slot, notice: 'Slot was successfully updated.'
      end
    else
      flash[:error] = "Slot has been reserved and cannot be changed"
    end
    return render :edit
  end

  def destroy
    if @slot.can_cancel?(current_user.nanny) && @slot.destroy
      redirect_to slots_url, notice: 'Slot was successfully deleted.'
    else
      redirect_to slots_path, alert: "You cannot delete a slot that has been reserved"
    end
  end

  private

    def set_slot
      @slot = Slot.find(params[:id])
    end


    def slot_params
      params.require(:slot).permit(:start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper


  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end

  def format_time(datetime)
    datetime.strftime("%b %d - %H:%M")
  end

end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/nannies_helper.rb
module NanniesHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>

      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_path %>">Schedule</a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
            <% if current_user && current_user.is_family? %>
              <li><a href="<%= nannies_path %>">Nannies</a></li>
            <% end %>

            <% if current_user && current_user.is_nanny? %>
              <li><a href="<%= slots_path %>">Slots</a></li>
            <% end %>
            </ul>

            <ul class="nav navbar-nav pull-right">
              <% if current_user %>
                <li><%= link_to current_user.name, edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>

      <div class="container">

<!--         <div class="starter-template">
          <h1>Welcome</h1>
          <p class="lead">Start by signing up for the application</p>
          SIGN UP BUTTON LOGIN BUTTON
        </div>
 -->
        <%= flash_messages %>
        <%= yield %>

      </div><!-- /.container -->
    </body>
</html>

app/views/nannies/index.html.erb
<div class="col-md-12">
  <h3>Filters</h3>
  <%= form_tag("/nannies", method: :get) do %>
  <%= label_tag "Start Date" %>
  <%= select_datetime @start_time, prefix:"start_time", minute_step: 15, start_year: 2017, end_year: 2017 %>
  <br>
  <%= label_tag "End Date" %>
  <%= select_datetime @end_time, prefix:"end_time", minute_step: 15 %>
  <br>
  <%= submit_tag "Filter", class: "btn btn-primary" %>
  <% end %>
</div>


<div class="col-md-12">
  <h3>Nannies that are free between <%= @start_time.strftime("%b %d - %H:%M") %> and <%= @end_time.strftime("%b %d - %H:%M") %></h3>
  <table class='table table-responsive'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Available Slots</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @nannies.each do |nanny| %>
        <tr>
          <td><%= nanny.name %></td>
          <td>
            <% nanny.slots.each do |s| %>
              <div>
                <%= format_time(s.start_time)  %> - <%= format_time(s.end_time) %> |
                <%= link_to "Reserve", reserve_nanny_path(s), method: :patch %>
              </div>
            <% end %>
          </td>
          <td><%= link_to "View All", nanny_path(nanny) %></td>
        </tr>
      <% end %>
    </tbody>

  </table>

</div>

app/views/nannies/show.html.erb
<div class='col-md-12'>
  <h2><%= @nanny.name %></h2>
</div>

<div class='col-md-6'>
  <h4>Available Slots</h4>
  <table class="table">
    <tr>
      <th>From</th>
      <th>To</th>
      <th></th>
    </tr>

    <% @nanny.slots.reserveable.each do |slot| %>
      <tr>
        <td><%= format_time(slot.start_time) %></td>
        <td><%= format_time(slot.end_time) %></td>
        <td><%= link_to "Reserve", reserve_nanny_path(slot), method: :patch, class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </table>

</div>

app/views/slots/_form.html.erb
<%= form_for(slot) do |f| %>
  <% if slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
      <% slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time, start_year: 2017, end_year: 2017 %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time, start_year: 2017, end_year: 2017 %>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/slots/edit.html.erb
<h1>Editing Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Show', @slot %> |
<%= link_to 'Back', slots_path %>

app/views/slots/index.html.erb
<div class="col-md-12">
  <p id="notice"><%= notice %></p>

  <h1>Slots</h1>

  <table class='table'>
    <thead>
      <tr>
        <th>Start time</th>
        <th>End time</th>
        <th>Reserved By</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @slots.each do |slot| %>
        <tr>
          <td><%= format_time(slot.start_time) %></td>
          <td><%= format_time(slot.end_time) %></td>
          <td><%= slot.family.try(:name) %></td>
          <td><%= link_to 'Modify', edit_slot_path(slot) if slot.can_edit?(current_user.nanny) %></td>
          <td><%= link_to 'Delete', slot, method: :delete, data: { confirm: 'Are you sure?' } if slot.can_cancel?(current_user.nanny) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if @slots.empty? %>
    <div class="starter-template">
      <h1>Welcome</h1>
      <p class="lead">Start by creating a slot</p>
    </div>
  <% end %>

  <br>

  <%= link_to 'New Slot', new_slot_path, class:"btn btn-primary" %>

</div>

app/views/slots/new.html.erb
<div class='col-md-12'>
  <h1>New Slot</h1>

  <br>
  <section>
    <h4>A few things to keep in mind</h4>
      <li>Slots must start a minimum of 15 minutes from now.</li>
      <li>They should be a minimum of 30 minutes.</li>
      <li>You cant have 2 overlapping slots.</li>
  </section>

  <br>
  <%= render 'form', slot: @slot %>

  <%= link_to 'Back', slots_path %>

</div>

app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @slot.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @slot.end_time %>
</p>

<p>
  <strong>Family:</strong>
  <%= @slot.family %>
</p>

<p>
  <strong>Nanny:</strong>
  <%= @slot.nanny %>
</p>

<%= link_to 'Edit', edit_slot_path(@slot) %> |
<%= link_to 'Back', slots_path %>